project:
  type: website

website:
  title: "Ingenieria y Arquitectura Asistidas por Sistemas Inteligentes (IAASI)"

  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: docs/chapters/01-intro/index.qmd
        text: Introducción

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introducción"
        href: docs/chapters/01-intro/index.qmd
        contents:
          - docs/chapters/01-intro/index.qmd
          - docs/chapters/01-intro/01-imperativa.qmd
          - docs/chapters/01-intro/02-funcional.qmd
          - docs/chapters/01-intro/03-natural.qmd
          - docs/chapters/01-intro/04-ia_simbolica.qmd
          - docs/chapters/01-intro/05-ml.qmd
          - docs/chapters/01-intro/06-dl.qmd
          - docs/chapters/01-intro/07-watson.qmd
          - docs/chapters/01-intro/08-llm.qmd
          
bibliography:
   - referencias/historia-ia.bib
   - referencias/inteligencia-artificial.bib
   - referencias/historia-software.bib
   - referencias/ingenieria-software.bib          

link-citations: true
lang: es      
   
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    number-depth: 3
    
execute:
  freeze: auto
  
