project:
  type: website

website:
  title: "Ingenieria y Arquitectura Asistidas por Sistemas Inteligentes (IAASI)"

  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: chapters/01-intro/index.qmd
        text: Introducción
      - href: chapters/02-conceptos/index.qmd
        text: Conceptos
      - href: chapters/03-foundations/index.qmd
        text: Foundations

  sidebar:
    style: "docked"
    search: true
    contents: chapters
          
bibliography:
   - referencias/historia-ia.bib
   - referencias/inteligencia-artificial.bib
   - referencias/historia-software.bib
   - referencias/ingenieria-software.bib          

link-citations: true
lang: es      
   
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    number-depth: 3
    
execute:
  freeze: auto
  
